#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MusicXMLViewer.Android.Resource", IsApplication=true)]

namespace MusicXMLViewer.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::MusicXMLViewer.Android.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::MusicXMLViewer.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int my_accent = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int my_primary = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int my_statusbar = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int my_textcolor = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int my_textdark = 2131034116;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int file = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int folder = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int recent = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000a
			public const int RelativeLayout1 = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int button2 = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int details = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int file_list_fragment = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int file_picker_image = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int file_picker_text = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int gridViewRecentFiles = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int menuItem = 2131230736;
			
			// aapt resource value: 0x7f080005
			public const int notationLayout = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int pager = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int progressBarFileOpening = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int progressLayout = 2131230726;
			
			// aapt resource value: 0x7f08000f
			public const int switchForActionBar = 2131230735;
			
			// aapt resource value: 0x7f080008
			public const int textViewLoading = 2131230728;
			
			// aapt resource value: 0x7f08000e
			public const int textViewRecentFile = 2131230734;
			
			// aapt resource value: 0x7f080002
			public const int titles_fragment = 2131230722;
			
			// aapt resource value: 0x7f08000b
			public const int viewPage = 2131230731;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int file_explorer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int file_picker_list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notation = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notation_page = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int recent_files = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RecentFileItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int switcher = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int button_file_system_text = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int no_files_or_directories = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int recentFilesCount = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int myCustomMenuTextApearance = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
